### ISSUE TITLE
Post-Deliverable Checklist

### ISSUE THREAD

**Issue by Marissa96** [sandheather/simple-chat-app#10]
1) Your progress so far [1.75%]
2) All the issues you created (and hopefully completed) for the past deliverable. [1.75%]
3) Anything you found was a positive from the past few weeks minimum of 2 [1.75%]
4) Anything you found didn't work out so well from the past few weeks [1.75%]
5) Ask @ericadamski for feedback on a part of your project. minimum of 1 [1.75%]

# Progress
- [x] Paper Wireframes
  - [x] 404 page
  - [x] Chat (main) page
  - [x] Members List
  - [x] Notifications
    - [x] Joined
    - [x] Left

**Comment by sandheather** [comment]
# Issues
Completed: #4 

# Positives :+1:

+ succeeded in wire framing 
+ enjoyed developing concept

# Improvements :star:

+ post ideas and comments mid week so more information is passed around

# Request for Feedback :ear:

+ is there enough information in our wireframes? Is our concept clear?

**Comment by Marissa96** [comment]
Issues
Completed: #8 

Positives 👍
I had an easy time coming up with layout ideas
Made great wireframes!

Improvements ⭐️
Time Management

**Comment by emilycopp** [comment]
# Issues
- Completed: #2 

# Positives 👍
- Easily defined corgi theme across all pages 
- Wireframes are laid out nicely

# Improvements ⭐️
- More communication with team members about project
